name: CI

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: zulu

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test
      - run: dart analyze
